services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./apps/auth-service:/challenge/apps/auth-service
      - ./packages:/challenge/packages
      - ./package.json:/challenge/package.json
      - ./pnpm-lock.yaml:/challenge/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/challenge/pnpm-workspace.yaml
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - ./.env
      - ./apps/auth-service/.env
    depends_on:
      - db
    networks:
      - challenge-network
    restart: unless-stopped

  tasks-service:
    container_name: tasks-service
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./apps/tasks-service:/challenge/apps/tasks-service
      - ./packages:/challenge/packages
      - ./package.json:/challenge/package.json
      - ./pnpm-lock.yaml:/challenge/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/challenge/pnpm-workspace.yaml

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${TASKS_SERVICE_PORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
    env_file:
      - ./.env
      - ./apps/tasks-service/.env
    depends_on:
      - db
      - rabbitmq
    networks:
      - challenge-network
    restart: unless-stopped

  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - challenge-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - challenge-network
    env_file:
      - ./.env
    volumes: ["rabbitmq_data:/var/lib/rabbitmq"]

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  challenge-network:
    driver: bridge
